# Site settings
title: Programming
email: csaba.trucza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stuff about programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ctrucza.github.io" # the base hostname & protocol for your site
twitter_username: ctrucza
github_username:  ctrucza

# Build settings
highlighter: true
markdown: kramdown
